language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

branches:
 only:
   - master
   
addons:
  apt:
    packages:
      - libssl-dev
      - libssh2-1-dev
      - libcurl4-openssl-dev

before_install:
 - date -u
 - uname -a
 - env | grep -v "BINTRAY_API_KEY" | sort
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                     ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl                            ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink openssl && brew link openssl --force; fi 

install: true

script: ./build.libgit2.sh

after_success: ./uploadbinaries.sh
